### ISSUE TITLE
PwnedPhysics does not work on mod after 105 version

### ISSUE THREAD

**Issue by sous-park** [NotARobot6969/PwnedPhysics#1]
Hey, author of physic mod changed somthing, and your Pwned dosen't work now. 

UPD author just changed port to 8080,

Fix: 
app.listen(4567, () => {
    console.log(`Listening on port 4567`)

to 

app.listen(8080, () => {
    console.log(`Listening on port 8080`)
into app.js

**Comment by not-nullptr** [comment]
sorry, didn't see this. bit busy rn, could u make a pr for this issue?

**Comment by not-nullptr** [comment]
pushed a fix. kind of janky, but will work.
