### ISSUE TITLE
its just giving me connection refused no further information

### ISSUE THREAD

**Issue by MommyLexie** [NotARobot6969/PwnedPhysics#2]
![image](https://user-images.githubusercontent.com/81419755/216376780-d59d5a8d-328a-4b37-a03e-d1a68649799c.png)

**Comment by not-nullptr** [comment]
oops, sorry, wrong port, i'll fix rn

**Comment by not-nullptr** [comment]
should be fixed now!

**Comment by ButanikuMC** [comment]
I'm also having this issue when opening Minecraft, I see the verification screen and it shows up this error so I can't use the allowedCodes
