### ISSUE TITLE
It shows "connection refused: no further information"

### ISSUE THREAD

**Issue by ButanikuMC** [NotARobot6969/PwnedPhysics#3]
I have tried changing oldversion, using allowedcodes, and nothing, it shows up the Verification screen with that error.

**Comment by not-nullptr** [comment]
might have fixed it? im not on an environment where i can test it

**Comment by ButanikuMC** [comment]
It still shows the error unfortunately.

**Comment by ButanikuMC** [comment]
> might have fixed it? im not on an environment where i can test it

Looks like my jar was broken and that fix didn't fix it, I found another and it worked
